"""Export an upper certificate as Lean data, numerical checks and tree assembly.

Compilation checks the generated numerical proofs with Lean's `decide +kernel`.
The verifier holds the generated-directory lock throughout export and checking.
"""

from fractions import Fraction
import gzip
import hashlib
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import ROOT, atomic_json, atomic_text, file_snapshot
from exact import Geometry, inputs

NS = "MoserWorm.UpperBound.Certificate"
GEN = NS + ".Generated"
SHARD_SIZE = 8


def kq(q):
    q = Fraction(q)
    return f"({q.numerator}, {q.denominator - 1})"


def kq2(v):
    return f"({kq(v[0])}, {kq(v[1])})"


def rect_text(r):
    return "(" + ", ".join(map(str, r)) + ")"


def list_text(xs):
    return "[" + ", ".join(xs) + "]"


def spec_text(s):
    if s[0] == "flush":
        return f"(.flush {s[1]} {str(bool(s[2])).lower()} {str(bool(s[3])).lower()})"
    return f"(.{s[0]} {kq(s[1])} {str(bool(s[2])).lower()})"


def trie_text(values, height):
    def go(index, stride, h):
        if index >= len(values):
            return f"(KVec.full none {h})"
        return (
            f"(.node {values[index]} {go(index + stride, stride*2, h-1)} "
            f"{go(index + 2*stride, stride*2, h-1)})"
        )

    return go(0, 1, height)


def export_sources():
    return file_snapshot(
        [
            Path(__file__),
            Path(__file__).with_name("exact.py"),
            Path(__file__).parents[1] / "common.py",
        ],
        ROOT,
    )


def export(certificates, output):
    # Publish incomplete before validation or overwriting any generated source.
    atomic_json(output / "manifest.json", {"schema": 1, "complete": False, "modules": []})
    sources = export_sources()
    snapshot, metadata, manifest = inputs(certificates)
    if metadata["complete"] is not True:
        raise ValueError("upper certificate is incomplete")
    with gzip.open(certificates / "tree.json.gz", "rt") as f:
        tree = json.load(f)
    paths = {}

    def collect_paths(node, assign, rect):
        if node[0] == "l":
            if node[1] in paths:
                raise ValueError("repeated leaf in tree")
            paths[node[1]] = [assign, rect]
        elif node[0] == "p":
            collect_paths(node[2], [(node[1], 0)] + assign, rect)
            collect_paths(node[3], [(node[1], 1)] + assign, rect)
        elif node[0] == "s":
            for cell, child in node[1]:
                collect_paths(child, assign, cell)
        else:
            raise ValueError("unknown tree node")

    collect_paths(tree, [], [0, metadata["kR"], 0, metadata["kL"]])
    leaves = []
    for name in manifest["files"]:
        with gzip.open(certificates / name, "rt") as f:
            leaves.extend(json.loads(line) for line in f)
    geom = Geometry(metadata["specs"])
    if [geom.kR, geom.kL] != [metadata["kR"], metadata["kL"]]:
        raise ValueError("label count mismatch")
    modules, hashes = [], {}

    def emit(name, imports, body):
        text = (
            "/- Generated by scripts/upper/export.py. -/\n"
            + "".join(f"import {imp}\n" for imp in imports)
            + "set_option linter.style.longLine false\n"
            "set_option linter.style.setOption false\n"
            "set_option maxRecDepth 1000000\n"
            "set_option maxHeartbeats 0\n"
            + f"namespace {GEN}\nopen {NS} {NS}.Kernel\n\n"
            + body
            + f"\nend {GEN}\n"
        )
        atomic_text(output / (name + ".lean"), text)
        module = GEN + "." + name
        modules.append(
            {"name": module, "dependencies": [imp for imp in imports if imp.startswith(GEN + ".")]}
        )
        hashes[module] = hashlib.sha256(text.encode()).hexdigest()

    def chunked_list(name, ty, values):
        chunks = [values[i : i + 128] for i in range(0, len(values), 128)]
        parts = [
            f"noncomputable def {name}{i} : List ({ty}) := {list_text(chunk)}"
            for i, chunk in enumerate(chunks)
        ]
        parts.append(
            f"noncomputable def {name} : List ({ty}) := "
            + " ++ ".join(f"{name}{i}" for i in range(len(chunks)))
        )
        return parts

    lines = chunked_list("specsL", "KPSpec", list(map(spec_text, geom.specs)))
    for i, (coeffs, const) in enumerate(geom.erows):
        pairs = [f"({label}, {kq2(v)})" for label, v in coeffs]
        lines.append(f"noncomputable def erow{i} : KRow := ⟨{list_text(pairs)}, {kq(const)}⟩")
    lines += chunked_list(
        "eRowsL", "Option KRow", [f"some erow{i}" for i in range(len(geom.erows))]
    )
    lines.append(
        "noncomputable def kctxData : KCtx := {\n"
        f"  kR := {geom.kR}, kL := {geom.kL},\n"
        f"  right := {list_text(map(kq2, geom.right))},\n"
        f"  left := {list_text(map(kq2, geom.left))},\n"
        "  eRows := eRowsL,\n"
        "  target := kQ1 }"
    )
    emit("Data", [NS + ".Kernel.Header"], "\n\n".join(lines))

    # Explicit tries share the named row constants with the eRows list.
    # Equality to the canonical constructions is proved once by the kernel.
    ev = [f"(some erow{i})" for i in range(len(geom.erows))]
    nt = trie_text([kq2(v) for v in geom.normals], geom.n.bit_length() + 1)
    nt = nt.replace("KVec.full none", "KVec.full kQ2z")
    et = trie_text(ev, len(ev).bit_length() + 1)
    emit(
        "Tries",
        [GEN + ".Data"],
        f"noncomputable def normalsTrie : KVec KQ2 := {nt}\n\n"
        f"noncomputable def escapeTrie : KVec (Option KRow) := {et}\n\n"
        "theorem normalsTrie_eq : normalsTrie = KVec.ofList kQ2z\n"
        "    ((List.range (3 + kctxData.kR + kctxData.kL)).map\n"
        "      (kNormalOf kctxData.kR kctxData.right kctxData.left)) := by rfl\n\n"
        "theorem escapeTrie_eq : escapeTrie = KVec.ofList none kctxData.eRows := by rfl\n",
    )

    emit(
        "Labels",
        [GEN + ".Data"],
        "theorem buildOK : buildLabels (specsL.map decodePSpec) =\n"
        "    some (decodeCtx kctxData).T := by decide +kernel\n\n"
        "theorem labelsOK_checked : labelsOK (decodeCtx kctxData).T = true := by decide +kernel\n",
    )
    emit(
        "Orientations",
        [GEN + ".Data"],
        "theorem orthoOK : (specsL.map decodePSpec).all\n"
        "    (fun p => isOrtho (specMap p)) = true := by decide +kernel\n",
    )
    emit(
        "Header",
        [GEN + ".Labels", GEN + ".Orientations"],
        "theorem rows_present : (decodeCtx kctxData).eRows.all Option.isSome = true :=\n"
        "  decodeCtx_rows_present kctxData (by decide +kernel)\n",
    )
    row_cuts = []
    for i, lo in enumerate(range(0, len(geom.erows), 64)):
        n = min(64, len(geom.erows) - lo)
        row_cuts.append((lo, n))
        emit(
            f"Rows{i}",
            [GEN + ".Data"],
            f"theorem rowsOK{i} : (List.range' {lo} {n}).all (fun k =>\n"
            "    eRowAtL (specsL.map decodePSpec) (decodeCtx kctxData).T\n"
            "      (namedByAngle (decodeCtx kctxData).T) k ==\n"
            "        (decodeCtx kctxData).eRows.getD k none) = true := by decide +kernel\n",
        )

    def key_text(key):
        floor = geom.n**2
        if key < floor:
            d, p = divmod(key, geom.n)
            return f"(.s {d} {p})"
        if key == floor:
            return ".n"
        m, r = divmod(key - floor - 1, 2)
        return f"(.e {m} {r})"

    shard_count = 0
    for shard, lo in enumerate(range(0, len(leaves), SHARD_SIZE)):
        shard_count += 1
        body = []
        obs = []
        for index, den, pairs in leaves[lo : lo + SHARD_SIZE]:
            if den <= 0 or not pairs or any(n <= 0 for _, n in pairs):
                raise ValueError("nonpositive certificate multiplier or denominator")
            body.append(f"noncomputable def den{index} : Nat := {den - 1}")
            mus = [f"({key_text(k)}, ({n}, den{index}))" for k, n in pairs]
            body.append(
                f"noncomputable def mu{index} : List (RowKey × KQ) :=\n  "
                + ",\n  ".join(["[" + mus[0]] + mus[1:])
                + "]"
            )
            body.append(f"noncomputable def leaf{index} : KTree := .leaf mu{index}")
            assign, rect = paths[index]
            assignments = list_text(f"({m}, {r})" for m, r in assign)
            obs.append(f"(leaf{index}, {assignments}, {rect_text(rect)})")
        body.append(f"noncomputable def obs{shard} : List KOb := " + list_text(obs))
        body.append(
            f"theorem checked{shard} : kCheckPrepared kctxData normalsTrie escapeTrie\n"
            f"    968 obs{shard} = true := by decide +kernel"
        )
        body.append(
            f"theorem accepted{shard} : ∀ ob ∈ obs{shard},\n"
            "    checkTree (decodeCtx kctxData) 968 (decodeTree ob.1)\n"
            "      ob.2.1 ob.2.2 = true :=\n"
            f"  checkPrepared_sound _ _ _ normalsTrie_eq escapeTrie_eq _ _ checked{shard}"
        )
        emit(f"Shard{shard}", [GEN + ".Tries"], "\n\n".join(body))

    if [x[0] for x in leaves] != list(range(metadata["leaves"])):
        raise ValueError("missing or repeated leaf index")
    if set(paths) != set(range(metadata["leaves"])):
        raise ValueError("tree leaves do not match the certificate frontier")

    def skeleton(node):
        if node[0] == "l":
            return f"leaf{node[1]}"
        if node[0] == "p":
            return f"(.pl {node[1]} {skeleton(node[2])} {skeleton(node[3])})"
        if node[0] == "s":
            return (
                "(.split " + list_text(f"({rect_text(r)}, {skeleton(t)})" for r, t in node[1]) + ")"
            )
        raise ValueError("unknown tree node")

    # Right associativity keeps the membership proof linear.
    obs_sum = (
        "".join(f"(obs{i} ++ " for i in range(shard_count - 1))
        + f"obs{shard_count - 1}"
        + ")" * (shard_count - 1)
    )
    emit(
        "Tree",
        [GEN + f".Shard{i}" for i in range(shard_count)],
        f"noncomputable def ktreeData : KTree := {skeleton(tree)}\n\n"
        f"theorem topOK : kCutTop kctxData.eRows.length 32 ktreeData []\n"
        f"    (0, {geom.kR}, 0, {geom.kL}) = true := by decide +kernel\n\n"
        f"theorem frontierEq : kCutFrontier 32 ktreeData [] (0, {geom.kR}, 0, {geom.kL}) =\n"
        f"    {obs_sum} := by rfl\n",
    )
    body = [
        "noncomputable def kCertData : KCert := ⟨"
        + ", ".join(
            [kq(q) for q in metadata["t"] + metadata["h"]]
            + ["kQ1", str(geom.kR), str(geom.kL), "specsL", "ktreeData"]
        )
        + "⟩",
        "noncomputable def theCert : Cert := decodeCert kCertData",
        "theorem specs_toList : theCert.specs.toList = specsL.map decodePSpec := rfl",
        "private noncomputable def erF : Nat → Bool := fun k =>\n"
        "  eRowAtL (specsL.map decodePSpec) (decodeCtx kctxData).T\n"
        "    (namedByAngle (decodeCtx kctxData).T) k == (decodeCtx kctxData).eRows.getD k none",
    ]
    total = 0
    for i, (_, n) in enumerate(row_cuts):
        term = (
            f"rowsOK{i}" if i == 0 else f"all_range'_glue erF 0 {total} {n} rowsAll{i-1} rowsOK{i}"
        )
        total += n
        body.append(
            f"private theorem rowsAll{i} : (List.range' 0 {total}).all erF = true := {term}"
        )
    body.append(
        "private theorem rows_identity : eRowsArr theCert (decodeCtx kctxData).T\n"
        "    (namedByAngle (decodeCtx kctxData).T) = (decodeCtx kctxData).eRows :=\n"
        "  her_of theCert (specsL.map decodePSpec) specs_toList _ _ _\n"
        f"    (by decide +kernel) rowsAll{len(row_cuts)-1}"
    )
    body.append(
        "private theorem all_obligations : ∀ ob ∈ kCutFrontier 32 ktreeData []\n"
        f"    (0, {geom.kR}, 0, {geom.kL}), checkTree (decodeCtx kctxData) 968\n"
        "      (decodeTree ob.1) ob.2.1 ob.2.2 = true := by\n"
        "  rw [frontierEq]\n"
        + "".join(
            f"  refine List.forall_mem_append.mpr ⟨accepted{i}, ?_⟩\n"
            for i in range(shard_count - 1)
        )
        + f"  exact accepted{shard_count - 1}"
    )
    body.append(
        "theorem certOK : checkCert theCert = true :=\n"
        "  checkCert_of_kernel kCertData kctxData 32 (by omega)\n"
        "    (by decide +kernel) orthoOK buildOK (by rfl) (by rfl)\n"
        "    labelsOK_checked rows_identity rows_present (by rfl) topOK all_obligations"
    )
    emit(
        "Assembly",
        [GEN + ".Tree", GEN + ".Header"] + [GEN + f".Rows{i}" for i in range(len(row_cuts))],
        "\n\n".join(body),
    )
    build = {
        "schema": 1,
        "complete": metadata["complete"],
        "modules": modules,
        "shards": shard_count,
        "row_modules": len(row_cuts),
        "leaves": len(leaves),
        "shard_size": SHARD_SIZE,
        "sha256": hashes,
        "inputs": snapshot,
        "sources": sources,
    }
    if inputs(certificates)[0] != snapshot or export_sources() != sources:
        raise ValueError("upper inputs or exporter sources changed during export")
    atomic_json(output / "manifest.json", build)
    print(f"generated {len(modules)} modules; {len(leaves)} leaves; {shard_count} shards")
    return build
