#!/usr/bin/env python3
"""Export lower trees as Lean data, numerical checks and split joins.

Compilation verifies the numerical checks with `decide +kernel` and the joins
against the reconstructed boxes.
"""

from dataclasses import dataclass
import gzip
import hashlib
import json

import checker
import chord
from certificate import inputs
from common import atomic_text

MODULE = "MoserWorm.LowerBound.Certificate.Generated"
HEADER = """-- Generated by scripts/lower/export.py.
import MoserWorm.LowerBound.Certificate.RootBasic
import MoserWorm.LowerBound.Certificate.Chord.Basic
"""
OPTIONS = """open MoserWorm MoserWorm.LowerBound.Certificate
set_option maxRecDepth 1000000
set_option maxHeartbeats 0
"""
ASSEMBLY_OPTIONS = (
    "set_option linter.style.longLine false\nset_option linter.style.setOption false\n" + OPTIONS
)


def box_literal(box):
    return "#v[" + ", ".join(f"⟨{a.lo}, {a.hi}⟩" for a in box) + "]"


def is_leaf(tree):
    return isinstance(tree, (chord.PlainLeaf, chord.AnnotatedLeaf))


def witness_literal(witness):
    if isinstance(witness, chord.Terminal):
        return ".terminal"
    if isinstance(witness, chord.Rotate):
        return f".rotate {witness.offset} ({witness_literal(witness.child)})"
    if isinstance(witness, chord.Cut):
        nz = witness.nonzero
        if isinstance(nz, chord.Coordinate):
            nonzero = ".coordinate"
        elif isinstance(nz, chord.Side):
            nonzero = f".side {nz.label} {str(nz.reversed).lower()}"
        else:
            raise ValueError("unknown nonzero witness")
        return (
            f".cut {witness.i} {witness.j} {str(witness.positive_right).lower()} "
            f"({nonzero}) ({witness_literal(witness.left)}) "
            f"({witness_literal(witness.right)})"
        )
    raise ValueError("unknown polygon witness")


def annotated_literal(leaf):
    if isinstance(leaf, chord.PlainLeaf):
        members = [(fan, chord.Terminal()) for fan in leaf.fans]
    elif isinstance(leaf, chord.AnnotatedLeaf):
        members = [(member.fan, member.witness) for member in leaf.members]
    else:
        raise ValueError("expected a decoded annotated-format leaf")
    return (
        "["
        + ", ".join(
            "{ fan := { weight := "
            + str(fan.weight)
            + ", labels := ["
            + ", ".join(map(str, fan.labels))
            + "] }, witness := "
            + witness_literal(witness)
            + " }"
            for fan, witness in members
        )
        + "]"
    )


def tree_literal(tree):
    if isinstance(tree, Reference):
        return f"{tree.name}.tree"
    if is_leaf(tree):
        return ".leaf " + annotated_literal(tree)
    axis, left, right = tree
    return f".split {axis} ({tree_literal(left)}) ({tree_literal(right)})"


def edge_work(a, b):
    def owner(label):
        return -1 if label < 2 else (0 if label < 5 else (1 if label < 9 else 2))

    a, b = owner(a), owner(b)
    if a < 0 and b < 0:
        return 1
    if a < 0 or b < 0:
        return 12
    return 17 if a == b else 72


def triangle_work(a, b, c):
    return edge_work(a, b) + edge_work(b, c) + edge_work(c, a)


def fan_work(labels):
    if len(labels) <= 5:
        return 0
    return sum(triangle_work(labels[0], labels[1], p) for p in labels[2:]) + sum(
        triangle_work(labels[0], a, b) for a, b in zip(labels[2:-1], labels[3:])
    )


def leaf_work(leaf):
    """Estimate expanded terms so a large mixture gets its own kernel check."""
    work = 0
    for _, labels in leaf:
        work += sum(edge_work(a, b) for a, b in zip(labels, labels[1:] + labels[:1]))
        work += fan_work(labels)
    return work


def chord_leaf_work(leaf):
    """Charge the original area and every proposed guard; never a validity test."""
    if isinstance(leaf, chord.PlainLeaf):
        members = [(fan, chord.Terminal()) for fan in leaf.fans]
    elif isinstance(leaf, chord.AnnotatedLeaf):
        members = [(member.fan, member.witness) for member in leaf.members]
    else:
        raise ValueError("expected a decoded annotated-format leaf")
    work = sum(
        edge_work(a, b)
        for fan, _ in members
        for a, b in zip(fan.labels, fan.labels[1:] + fan.labels[:1])
    )
    pending = [(fan.labels, witness) for fan, witness in members]
    while pending:
        labels, witness = pending.pop()
        if isinstance(witness, chord.Terminal):
            work += fan_work(labels)
        elif isinstance(witness, chord.Rotate):
            pending.append((chord.rotate_labels(labels, witness.offset), witness.child))
        elif isinstance(witness, chord.Cut):
            left, right = chord.arcs(labels, witness.i, witness.j)
            a, b = labels[witness.i], labels[witness.j]
            work += sum(triangle_work(a, b, k) for k in labels if k != a and k != b)
            if isinstance(witness.nonzero, chord.Side):
                work += triangle_work(a, b, witness.nonzero.label)
            elif isinstance(witness.nonzero, chord.Coordinate):
                work += 2 * edge_work(a, b)
            else:
                raise ValueError("unknown nonzero witness")
            pending.extend(((left, witness.left), (right, witness.right)))
        else:
            raise ValueError("unknown polygon witness")
    return work


@dataclass
class Pending:
    box: tuple
    tree: object
    leaves: int
    work: int
    local_leaves: int
    nodes: int


@dataclass
class Reference:
    name: str
    leaves: int
    work: int = 0
    local_leaves: int = 0
    nodes: int = 1


def references(tree):
    if isinstance(tree, Reference):
        return {tree.name}
    if is_leaf(tree):
        return set()
    return references(tree[1]) | references(tree[2])


def check_declarations(box, tree):
    return (
        f"noncomputable def box : PlacementBox := {box_literal(box)}\n"
        f"noncomputable def tree : BoxTree 9 Chord.AnnotatedLeaf := {tree_literal(tree)}\n"
        "theorem accepted : BoxTree.check Chord.checkAnnotatedLeaf box tree = true :=\n"
        "  by decide +kernel\n"
    )


def join_declarations(box, axis, left, right):
    return (
        f"noncomputable def box : PlacementBox := {box_literal(box)}\n"
        "noncomputable def tree : BoxTree 9 Chord.AnnotatedLeaf := "
        f".split {axis} {left}.tree {right}.tree\n"
        f"private theorem left_box : box.left {axis} = {left}.box := by decide +kernel\n"
        f"private theorem right_box : box.right {axis} = {right}.box := by decide +kernel\n"
        "theorem accepted : BoxTree.check Chord.checkAnnotatedLeaf box tree = true :=\n"
        f"  BoxTree.check_split (left_box.symm ▸ {left}.accepted)\n"
        f"    (right_box.symm ▸ {right}.accepted)\n"
    )


def grouped_declarations(node, namespace, work_limit):
    """Group checks by estimated work; check oversized leaves individually."""
    blocks = []

    def emit(body, leaves):
        name = f"{namespace}.Block{len(blocks)}"
        blocks.append(f"namespace {name}\n{body}end {name}\n")
        return Reference(name, leaves)

    def materialize(part):
        if isinstance(part, Reference):
            return part
        return emit(check_declarations(part.box, part.tree), part.leaves)

    def visit(box, tree):
        if isinstance(tree, Reference):
            return tree
        if is_leaf(tree):
            return Pending(box, tree, 1, chord_leaf_work(tree), 1, 1)
        axis, left, right = tree
        left_box, right_box = checker.split_box(box, axis)
        left, right = visit(left_box, left), visit(right_box, right)
        leaves, work = left.leaves + right.leaves, left.work + right.work
        if isinstance(left, Pending) and isinstance(right, Pending) and work <= work_limit:
            return Pending(
                box,
                (axis, left.tree, right.tree),
                leaves,
                work,
                left.local_leaves + right.local_leaves,
                1 + left.nodes + right.nodes,
            )
        left, right = materialize(left), materialize(right)
        return emit(join_declarations(box, axis, left.name, right.name), leaves)

    result = materialize(visit(node.box, node.tree))
    return "".join(blocks) + (
        f"namespace {namespace}\n"
        f"noncomputable def box : PlacementBox := {result.name}.box\n"
        f"noncomputable def tree : BoxTree 9 Chord.AnnotatedLeaf := {result.name}.tree\n"
        "theorem accepted : BoxTree.check Chord.checkAnnotatedLeaf box tree = true :=\n"
        f"  {result.name}.accepted\n"
        f"end {namespace}\n"
    )


class Exporter:
    def __init__(self, directory, leaf_limit, work_limit=4000, name_prefix=""):
        self.directory, self.leaf_limit = directory, leaf_limit
        self.work_limit = work_limit
        self.module_work_limit = 4 * work_limit
        self.name_prefix = name_prefix
        self.node_limit = max(8, 4 * leaf_limit)
        self.modules = []
        directory.mkdir(parents=True, exist_ok=True)

    def write(self, name, source, dependencies, leaves, kind, work=0):
        path = self.directory / f"{name}.lean"
        atomic_text(path, source)
        self.modules.append(
            {
                "name": f"{MODULE}.{name}",
                "dependencies": dependencies,
                "leaves": leaves,
                "kind": kind,
                "work": work,
                "sha256": hashlib.sha256(source.encode()).hexdigest(),
            }
        )

    def materialize(self, node):
        if isinstance(node, Reference):
            return node
        name = f"{self.name_prefix}Part{len(self.modules)}"
        namespace = f"{MODULE}.{name}"
        dependencies = sorted(references(node.tree))
        source = HEADER + "".join(f"import {dep}\n" for dep in dependencies) + OPTIONS
        if dependencies or node.work > self.work_limit:
            source += grouped_declarations(node, namespace, self.work_limit)
        else:
            source += f"namespace {namespace}\n"
            source += check_declarations(node.box, node.tree)
            source += f"end {namespace}\n"
        self.write(
            name,
            source,
            dependencies,
            node.leaves,
            "check" if node.local_leaves else "join",
            node.work,
        )
        return Reference(namespace, node.leaves)

    def join(self, box, axis, left, right):
        if (
            left.local_leaves + right.local_leaves > self.leaf_limit
            or 1 + left.nodes + right.nodes > self.node_limit
            or left.work + right.work > self.module_work_limit
        ):
            # Keep small siblings inline, including along an unbalanced spine.
            # Large pure joins are also materialized to bound aggregation files.
            def large(part):
                return (
                    part.local_leaves >= (self.leaf_limit + 1) // 2
                    or part.nodes >= self.node_limit // 2
                    or part.work >= (self.module_work_limit + 1) // 2
                )

            if large(left):
                left = self.materialize(left)
            if large(right):
                right = self.materialize(right)
        left_tree = left if isinstance(left, Reference) else left.tree
        right_tree = right if isinstance(right, Reference) else right.tree
        return Pending(
            box,
            (axis, left_tree, right_tree),
            left.leaves + right.leaves,
            left.work + right.work,
            left.local_leaves + right.local_leaves,
            1 + left.nodes + right.nodes,
        )

    def parse(self, stream, box):
        node = stream.read_node()
        if type(node) is not int:
            return Pending(box, node, 1, chord_leaf_work(node), 1, 1)
        left_box, right_box = checker.split_box(box, node)
        left, right = self.parse(stream, left_box), self.parse(stream, right_box)
        return self.join(box, node, left, right)


def export_part(directory, destination, record, box, leaf_limit):
    """Export one frontier tree with names independent of the other parts."""
    index = record["id"]
    if record["box"] != [[a.lo, a.hi] for a in box]:
        raise ValueError("frontier box mismatch")
    exporter = Exporter(destination, leaf_limit, name_prefix=f"P{index:06d}_")
    with gzip.open(directory / record["file"], "rb") as stream:
        reader = chord.StreamReader(stream, version=2)
        result = exporter.parse(reader, box)
        reader.finish()
        if type(record.get("nodes")) is not int or reader.nodes != record["nodes"]:
            raise ValueError("incorrect annotated node count")
    if result.leaves != record["leaves"]:
        raise ValueError("incorrect leaf count")
    result = exporter.materialize(result)
    return result, exporter.modules


def export(directory, destination, leaf_limit):
    """Bridge each complete part once, then join real bounds across the frontier."""
    _, metadata = inputs(directory)
    parts = {record["id"]: record for record in metadata["parts"]}
    exporter = Exporter(destination, leaf_limit)
    blocks, imports = [], []
    index, leaves = 0, 0

    def add(body):
        name = f"{MODULE}.Bound{len(blocks)}"
        blocks.append(f"namespace {name}\n{body}end {name}\n")
        return name

    def visit(box, remaining):
        nonlocal index, leaves
        if remaining:
            axis = checker.split_axis(box)
            lb, rb = checker.split_box(box, axis)
            left, right = visit(lb, remaining - 1), visit(rb, remaining - 1)
            return add(
                f"noncomputable def box : PlacementBox := {box_literal(box)}\n"
                f"private theorem left_box : box.left {axis} = {left}.box := by decide +kernel\n"
                f"private theorem right_box : box.right {axis} = {right}.box := by decide +kernel\n"
                "theorem areaBound : Chord.coordinateBoxBound box :=\n"
                f"  Chord.coordinateBoxBound_split {axis}\n"
                f"    (left_box.symm ▸ {left}.areaBound)\n"
                f"    (right_box.symm ▸ {right}.areaBound)\n"
            )
        record = parts[index]
        index += 1
        result, modules = export_part(directory, destination, record, box, leaf_limit)
        exporter.modules.extend(modules)
        imports.append(result.name)
        leaves += result.leaves
        return add(
            f"noncomputable def box : PlacementBox := {result.name}.box\n"
            "theorem areaBound : Chord.coordinateBoxBound box :=\n"
            f"  Chord.coordinateBoxBound_of_annotated {result.name}.accepted\n"
        )

    result = visit(checker.root_box(), metadata["frontier_depth"])
    source = (
        "-- Generated by scripts/lower/export.py.\n"
        "import MoserWorm.LowerBound.Certificate.Chord.Sound\n"
        + "".join(f"import {name}\n" for name in imports)
        + ASSEMBLY_OPTIONS
        + "".join(blocks)
        + f"namespace {MODULE}\n"
        + f"private theorem root_eq : root = {result}.box := by decide +kernel\n"
        + "theorem theCertificateSound : Chord.coordinateBoxBound root :=\n"
        + f"  root_eq.symm ▸ {result}.areaBound\n"
        + "theorem rootLowerBound :\n"
        + "    ∀ p : Placement, root.Mem (placementCoordinates p) →\n"
        + "      ENNReal.ofReal tau ≤ placementVolume p :=\n"
        + "  Chord.root_lower_bound_of_coordinateBoxBound theCertificateSound\n"
        + f"end {MODULE}\n"
    )
    exporter.write("Assembly", source, imports, leaves, "join")
    manifest = {
        "format": 2,
        "leaf_limit": leaf_limit,
        "node_limit": exporter.node_limit,
        "work_limit": exporter.work_limit,
        "module_work_limit": exporter.module_work_limit,
        "modules": exporter.modules,
    }
    atomic_text(destination / "manifest.json", json.dumps(manifest, separators=(",", ":")) + "\n")
    return manifest
