"""Pack large generated lower proofs without changing any proof declaration.

The caller holds the Generated directory lock. Inputs are the controlled output
of export.py; this is not a general Lean source transformer.
"""

import hashlib
import json
import os
from pathlib import Path
import re
import tempfile

from common import atomic_json
from export import ASSEMBLY_OPTIONS, MODULE, OPTIONS

MODULE_THRESHOLD = 40_000
WORK_LIMIT = 32_000
MODULE_LIMIT = 8
COMMENT = "-- Generated by scripts/lower/export.py.\n"
STEM = re.compile(r"(?:P[0-9]{6}_Part[0-9]+|RootPart[0-9]+|Part[0-9]+|Assembly)")
PACKED = re.compile(r"Packed[0-9]+")
GENERIC = {
    "MoserWorm.LowerBound.Certificate." + suffix
    for suffix in ("RootBasic", "Kernel.Checker", "Chord.Basic", "Complete", "Chord.Sound")
}
IMPORT = re.compile(r"import ([A-Za-z_][A-Za-z_0-9.]*)\n")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def stem(name):
    require(isinstance(name, str) and name.startswith(MODULE + "."), "invalid generated namespace")
    result = name[len(MODULE) + 1 :]
    require(STEM.fullmatch(result), "unsupported generated module name")
    return result


def source(directory, record):
    """Check the exact exporter header/import grammar; retain body bytes."""
    name = record["name"]
    path = directory / (stem(name) + ".lean")
    require(not path.is_symlink() and path.is_file(), "invalid generated source path")
    data = path.read_bytes()
    require(digest(data) == record["sha256"], "generated source checksum mismatch")
    text = data.decode("utf-8")
    require(
        "\r" not in text and "\t" not in text and text.startswith(COMMENT),
        "unsupported generated source header",
    )
    options = (
        ASSEMBLY_OPTIONS if name == MODULE + ".Assembly" and ASSEMBLY_OPTIONS in text else OPTIONS
    )
    before, separator, rest = text[len(COMMENT) :].partition(options)
    require(separator and rest, "missing generated options/body")
    imports = []
    for line in before.splitlines(keepends=True):
        match = IMPORT.fullmatch(line)
        require(match, "unsupported generated import")
        imports.append(match[1])
    require(len(imports) == len(set(imports)), "duplicate generated import")
    require(
        all(i.startswith(MODULE + ".") or i in GENERIC for i in imports),
        "unexpected generic import",
    )
    require(
        {i for i in imports if i.startswith(MODULE + ".")} == set(record["dependencies"]),
        "generated imports and dependencies disagree",
    )
    require(not any(token in rest for token in ("--", "/-", "-/")), "unexpected generated comment")
    require(
        not re.search(r"\b(?:axiom|sorry|admit|unsafe|native_decide)\b", rest),
        "unsupported generated proof",
    )
    scopes = []
    for line in rest.splitlines():
        stripped = line.lstrip()
        require(
            not re.match(
                r"(?:import|prelude|module|set_option|open|opaque|macro|syntax|attribute)\b|#",
                stripped,
            ),
            "unexpected generated command",
        )
        if not line or line.startswith(" "):
            continue
        if line.startswith("namespace "):
            scope = line[len("namespace ") :]
            allowed = (
                scope == MODULE or re.fullmatch(re.escape(MODULE) + r"\.Bound[0-9]+", scope)
                if name == MODULE + ".Assembly"
                else scope == name or re.fullmatch(re.escape(name) + r"\.Block[0-9]+", scope)
            )
            require(allowed, "unexpected generated declaration namespace")
            scopes.append(scope)
        elif line.startswith("end "):
            require(scopes and scopes.pop() == line[4:], "unbalanced generated namespace")
        else:
            require(
                scopes and line.startswith(("noncomputable def ", "private theorem ", "theorem ")),
                "unsupported generated declaration",
            )
    require(not scopes, "unclosed generated namespace")
    return imports, (options + rest).encode("utf-8")


def family(name):
    value = stem(name)
    return value.split("_", 1)[0] if "_" in value else "Root"


def pack_generated(directory, manifest):
    """Adapt only when more than 40,000 generated files would be imported."""
    records = manifest["modules"]
    require(isinstance(records, list) and records, "empty generated manifest")
    # Count join files too: every imported file consumes a mapping.
    if len(records) - 1 <= MODULE_THRESHOLD:
        return manifest
    require("packing" not in manifest, "expected fresh unpacked export")
    directory = Path(directory).absolute()
    require(
        directory.resolve() == directory and directory.is_dir(),
        "generated directory must not be a symlink",
    )
    manifest_path = directory / "manifest.json"
    require(not manifest_path.is_symlink(), "invalid generated manifest path")
    original_manifest = manifest_path.read_bytes()
    require(json.loads(original_manifest) == manifest, "generated manifest changed")
    entries = list(directory.iterdir())
    require(
        all(
            p.is_file()
            and not p.is_symlink()
            and (
                p.name == "manifest.json"
                or p.suffix == ".lean"
                and (STEM.fullmatch(p.stem) or PACKED.fullmatch(p.stem))
            )
            for p in entries
        ),
        "unexpected file in generated directory",
    )
    seen = set()
    for record in records:
        require(isinstance(record, dict), "invalid generated module record")
        name = record["name"]
        stem(name)
        require(name not in seen, "duplicate generated module")
        deps = record["dependencies"]
        require(
            isinstance(deps, list)
            and all(isinstance(d, str) for d in deps)
            and len(deps) == len(set(deps))
            and set(deps) <= seen,
            "generated modules must be a dependency-ordered DAG",
        )
        require(
            type(record["work"]) is int
            and record["work"] >= 0
            and record["kind"] in ("check", "join"),
            "invalid generated work/kind",
        )
        source(directory, record)
        seen.add(name)
    assembly = records[-1]
    require(
        assembly["name"] == MODULE + ".Assembly"
        and type(assembly["leaves"]) is int
        and assembly["leaves"] > 0,
        "missing final Assembly and leaf count",
    )
    by_name = {r["name"]: r for r in records}
    reached, pending = set(), [assembly["name"]]
    while pending:
        name = pending.pop()
        if name not in reached:
            reached.add(name)
            pending.extend(by_name[name]["dependencies"])
    require(reached == seen, "Assembly does not cover every generated module")
    groups, current, work = [], [], 0
    for record in records[:-1]:
        if current and (
            family(record["name"]) != family(current[0]["name"])
            or work + record["work"] > WORK_LIMIT
            or len(current) == MODULE_LIMIT
        ):
            groups.append(current)
            current, work = [], 0
        current.append(record)
        work += record["work"]
    if current:
        groups.append(current)
    owner = {r["name"]: f"{MODULE}.Packed{i:06d}" for i, g in enumerate(groups) for r in g}
    output = []
    with tempfile.TemporaryDirectory(prefix=".lower-pack-", dir=directory.parent) as temporary:
        staged = Path(temporary)
        for i, group in enumerate(groups):
            name = f"{MODULE}.Packed{i:06d}"
            generic, bodies, constituents = set(), [], []
            deps = sorted({owner[d] for r in group for d in r["dependencies"] if owner[d] != name})
            for record in group:
                imports, body = source(directory, record)
                generic.update(x for x in imports if not x.startswith(MODULE + "."))
                bodies.append(body)
                constituents.append(
                    {
                        "name": record["name"],
                        "sha256": record["sha256"],
                        "body_sha256": digest(body),
                    }
                )
            data = (COMMENT + "".join(f"import {n}\n" for n in sorted(generic) + deps)).encode()
            data += b"".join(bodies)
            (staged / f"Packed{i:06d}.lean").write_bytes(data)
            output.append(
                {
                    "name": name,
                    "dependencies": deps,
                    "sha256": digest(data),
                    "work": sum(r["work"] for r in group),
                    "kind": "check" if any(r["kind"] == "check" for r in group) else "join",
                    "constituents": constituents,
                }
            )
        imports, body = source(directory, assembly)
        rewritten = sorted({owner.get(n, n) for n in imports})
        data = (COMMENT + "".join(f"import {n}\n" for n in rewritten)).encode() + body
        (staged / "Assembly.lean").write_bytes(data)
        output.append(
            {
                **assembly,
                "sha256": digest(data),
                "dependencies": sorted({owner[d] for d in assembly["dependencies"]}),
            }
        )
        result = {
            **manifest,
            "module_work_limit": WORK_LIMIT,
            "modules": output,
            "packing": {
                "version": 1,
                "threshold": MODULE_THRESHOLD,
                "module_limit": MODULE_LIMIT,
                "original_modules": len(records) - 1,
                "original_manifest_sha256": digest(original_manifest),
                "export_module_work_limit": manifest["module_work_limit"],
            },
        }
        # Validate everything before publication. The caller owns the directory lock
        # and will snapshot only after this function succeeds. A failed publish
        # aborts verification; the ordinary export recreates its inputs on retry.
        require(manifest_path.read_bytes() == original_manifest, "generated manifest changed")
        for record in records:
            source(directory, record)
        require(set(directory.iterdir()) == set(entries), "generated directory changed")
        names = {p.name for p in staged.iterdir()}
        for path in staged.iterdir():
            os.replace(path, directory / path.name)
        for path in entries:
            if path.suffix == ".lean" and path.name not in names:
                path.unlink()
        atomic_json(manifest_path, result)
    return result
